# Generated by Django 4.2.5 on 2023-10-03 07:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_registered_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
