# Generated by Django 4.2.5 on 2023-10-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0005_alter_userprofile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='games',
            field=models.CharField(blank=True, choices=[('valorant', 'Valorant'), ('csgo', 'Csgo'), ('pubg', 'Pubg')], max_length=100, null=True),
        ),
    ]
