# Generated by Django 4.2.5 on 2023-11-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0010_remove_customuser_max_otp_try_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='max_otp_try',
            field=models.IntegerField(default=10),
        ),
    ]
