# Generated by Django 4.2.5 on 2023-11-30 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0016_customuser_social_auth_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='social_auth_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
