# Generated by Django 4.2.5 on 2023-11-30 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0017_userprofile_social_auth_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='social_auth_key',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='social_auth_key',
        ),
    ]
