# Generated by Django 4.2.5 on 2023-11-30 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0019_userprofile_social_auth_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
