# Generated by Django 4.2.5 on 2023-12-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0023_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='social_auth_key',
        ),
        migrations.AddField(
            model_name='customuser',
            name='social_auth_key',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
