# Generated by Django 4.2.5 on 2023-12-01 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0024_remove_userprofile_social_auth_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='discord_auth_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
