# Generated by Django 4.2.5 on 2023-12-05 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0026_rename_discord_auth_code_customuser_discord_auth_key'),
    ]

    operations = [

        migrations.AddField(
            model_name='userprofile',
            name='gamer_name',
            field=models.CharField(blank=True, max_length=200, ),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=200),
        ),

    ]
