# Generated by Django 4.2.5 on 2023-12-05 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0030_alter_userprofile_gamer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pid',
            field=models.AutoField(default=django.utils.timezone.now, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
