# Generated by Django 4.2.5 on 2023-12-05 12:24

from django.db import migrations, models
import userauths.models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0031_alter_userprofile_pid_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pid',
            field=models.AutoField(default=userauths.models.generate_pid, primary_key=True, serialize=False),
        ),
    ]
