# Generated by Django 4.2.5 on 2023-12-05 12:31

from django.db import migrations, models
import userauths.models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0032_alter_userprofile_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pid',
            field=models.CharField(default=userauths.models.generate_pid, max_length=25, primary_key=True, serialize=False, unique=True),
        ),
    ]
