# Generated by Django 4.2.5 on 2023-10-21 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_friend'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('game_type', models.CharField(choices=[('valorant', 'Valorant'), ('pubg_mobile', 'PUBG Mobile'), ('csgo', 'CsGo')], max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('entry_fee', models.DecimalField(decimal_places=2, max_digits=6)),
                ('added_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournaments_added', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(related_name='tournaments_participating', to=settings.AUTH_USER_MODEL)),
                ('removed_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournaments_removed', to=settings.AUTH_USER_MODEL)),
                ('teams', models.ManyToManyField(related_name='tournaments_teams', to=settings.AUTH_USER_MODEL)),
                ('winning_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournaments_won', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
